### ISSUE TITLE
Can't access to match_gcdata through explorer endpoint

### ISSUE THREAD

**Issue by AndriiAkulov** [odota/core#1523]
When I try to execute query `SELECT
*
FROM match_gcdata
LIMIT 20000`

through explorer I have next error : 
`error: permission denied for relation match_gcdata
    at Connection.parseE (/usr/src/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/usr/src/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/usr/src/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)`

Why is permission denied?

**Comment by howardchung** [comment]
Explorer only allows access to a subset of tables.  If you're looking for replay salts, use the /replays endpoint

**Comment by AndriiAkulov** [comment]
@howardchung I am looking for the way to fetch all matches from the league(by league id) using one query. I've tried to fetch them using explorer, but it doesn't fetch all needed data. There is some way to do this?

**Comment by howardchung** [comment]
Currently, this isn't supported in a single query.  You could fetch the list of match IDs, then make a request with 10 match IDs at once to /replays.
