### ISSUE TITLE
unhandled exception `TimeoutError`

### ISSUE THREAD

**Issue by rezk2ll** [odota/core#1602]
Hello, 
when i try to use the explorer and use the hero-filter only i get an error message about an unhandled `TimeoutError` exception

```
TimeoutError: Defined query timeout of 10000ms exceeded when running query.
    at afterTimeout (/usr/src/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/usr/src/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

![image](https://user-images.githubusercontent.com/6764881/35826871-60298c18-0aba-11e8-8268-703ba8b49838.png)

**Comment by howardchung** [comment]
Do you have a sample query?  You may want to put a time/league filter to reduce the number of matches searched.
