### ISSUE TITLE
itemPopularity endpoint fails for some heroes

### ISSUE THREAD

**Issue by howardchung** [odota/core#2663]
e.g. https://api.opendota.com/api/heroes/5/itemPopularity

**Comment by howardchung** [comment]
Checked the logs and this parseInt is crashing:
```
/usr/src/store/queries.js:318
        const time = parseInt(item.time, 10);
                                   ^

TypeError: Cannot read properties of null (reading 'time')
    at /usr/src/store/queries.js:318:36
    at Array.map (<anonymous>)
    at /usr/src/store/queries.js:317:8
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    ```

@ff137

**Comment by ff137** [comment]
#2664
